# experiment parameter
SAMPLE_RATE: 16000                                                            # 采样率
WIN_LEN: 320                                                                  # 窗长
FFT_SIZE: 161                                                                 # fft大小
WIN_OFFSET: 160                                                               # 窗移
LR: 0.001                                                                     # 学习率
MAX_EPOCH: 15                                                                 # 训练轮数
EPSILON: 0.0000001                                                            #
USE_CV: False                                                                  # [True,False]，是否使用验证集
EVAL_STEP: 125                                                               # 多少个batch进行一次CV
LOG_STEP: 625                                                                 # 多少个batch输出一次信息


# server setting
CUDA_ID: '1'                                                                  # 指定GPU编号
BATCH_SIZE: 64                                                               # 批处理数
NUM_WORK: 0                                                                   # 线程数


# environment parameter
project_root_path: '/home/ZhangXueLiang/zhaofei/PycharmProject/Freshmen'                    # 项目根目录
WAV_PATH: '/data01/zhaofei/data/freshmen_practice_data/train_large'           # 语音文件路径
TEST_PATH: '/data01/fanhaipeng/NewStudent/course-v3/zh-nbs/test/'                    # 测试集路径
#CONFIG_PATH: '/data01/zhaofei/config'                                # 配置文件路径
TRAIN_LST: '/data01/zhaofei/data/freshmen_practice_data/train_large'
TRAIN_LABEL_PATH: '/data01/zhaofei/data/freshmen_practice_data/train_large_lab.txt'       # 噪音文件路径

CV_LST: '/data01/zhaofei/data/freshmen_practice_data/val'
CV_LABEL_PATH: '/data01/zhaofei/data/freshmen_practice_data/val.txt'

OUTPUT_DIR: '/data01/zhaofei/result/'                                          # 输出根目录
#OFFLINE_TEST_DIR: '/data_zkh/tt_result/'                                      # 本地测试数据输出路径
BEST_MODEL: 'best.ckpt'                                                       # 默认最好模型名称
MID_MODEL: 'val.ckpt'                                                         # 默认中间模型名称
SAVE_BEST_ONLY: False                                                         # [True,False]:[仅保存最好的模型,保存中间模型]
WORKSPACE: '/freshmen_challenge_maxpool'                                                        # 子项目名称